//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class attachments
    {
        public int id { get; set; }
        public Nullable<int> container_id { get; set; }
        public string container_type { get; set; }
        public string filename { get; set; }
        public string disk_filename { get; set; }
        public long filesize { get; set; }
        public string content_type { get; set; }
        public string digest { get; set; }
        public int downloads { get; set; }
        public int author_id { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string description { get; set; }
        public string disk_directory { get; set; }
    }
}
