//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class auth_sources
    {
        public int id { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public string host { get; set; }
        public Nullable<int> port { get; set; }
        public string account { get; set; }
        public string account_password { get; set; }
        public string base_dn { get; set; }
        public string attr_login { get; set; }
        public string attr_firstname { get; set; }
        public string attr_lastname { get; set; }
        public string attr_mail { get; set; }
        public bool onthefly_register { get; set; }
        public bool tls { get; set; }
        public string filter { get; set; }
        public Nullable<int> timeout { get; set; }
    }
}
