//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class changesets
    {
        public int id { get; set; }
        public int repository_id { get; set; }
        public string revision { get; set; }
        public string committer { get; set; }
        public System.DateTime committed_on { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> commit_date { get; set; }
        public string scmid { get; set; }
        public Nullable<int> user_id { get; set; }
    }
}
