//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class custom_fields
    {
        public int id { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public string field_format { get; set; }
        public string possible_values { get; set; }
        public string regexp { get; set; }
        public Nullable<int> min_length { get; set; }
        public Nullable<int> max_length { get; set; }
        public bool is_required { get; set; }
        public bool is_for_all { get; set; }
        public bool is_filter { get; set; }
        public Nullable<int> position { get; set; }
        public Nullable<bool> searchable { get; set; }
        public string default_value { get; set; }
        public Nullable<bool> editable { get; set; }
        public bool visible { get; set; }
        public Nullable<bool> multiple { get; set; }
        public string format_store { get; set; }
        public string description { get; set; }
    }
}
