//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class custom_values
    {
        public int id { get; set; }
        public string customized_type { get; set; }
        public int customized_id { get; set; }
        public int custom_field_id { get; set; }
        public string value { get; set; }
    }
}
