//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class custom_reports
    {
        public int id { get; set; }
        public Nullable<int> project_id { get; set; }
        public int user_id { get; set; }
        public bool is_public { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string group_by { get; set; }
        public string chart_type { get; set; }
        public string null_text { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
