//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_addresses
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string address { get; set; }
        public bool is_default { get; set; }
        public bool notify { get; set; }
        public System.DateTime created_on { get; set; }
        public System.DateTime updated_on { get; set; }
    }
}
