//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class enumerations
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> position { get; set; }
        public bool is_default { get; set; }
        public string type { get; set; }
        public bool active { get; set; }
        public Nullable<int> project_id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string position_name { get; set; }
    }
}
