//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class issue_relations
    {
        public int id { get; set; }
        public int issue_from_id { get; set; }
        public int issue_to_id { get; set; }
        public string relation_type { get; set; }
        public Nullable<int> delay { get; set; }
    }
}
