//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class issues
    {
        public int id { get; set; }
        public int tracker_id { get; set; }
        public int project_id { get; set; }
        public string subject { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<int> category_id { get; set; }
        public int status_id { get; set; }
        public Nullable<int> assigned_to_id { get; set; }
        public int priority_id { get; set; }
        public Nullable<int> fixed_version_id { get; set; }
        public int author_id { get; set; }
        public int lock_version { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public int done_ratio { get; set; }
        public Nullable<float> estimated_hours { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> root_id { get; set; }
        public Nullable<int> lft { get; set; }
        public Nullable<int> rgt { get; set; }
        public bool is_private { get; set; }
        public Nullable<System.DateTime> closed_on { get; set; }
    }
}
