//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class issue_categories
    {
        public int id { get; set; }
        public int project_id { get; set; }
        public string name { get; set; }
        public Nullable<int> assigned_to_id { get; set; }
    }
}
