//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class issue_template_settings
    {
        public int id { get; set; }
        public Nullable<int> project_id { get; set; }
        public string help_message { get; set; }
        public Nullable<bool> enabled { get; set; }
        public Nullable<bool> should_replaced { get; set; }
        public bool inherit_templates { get; set; }
    }
}
