//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class itsmreporting_operationsEntities : DbContext
    {
        public itsmreporting_operationsEntities()
            : base("name=itsmreporting_operationsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mail_send_of_percentage> mail_send_of_percentage { get; set; }
        public virtual DbSet<sla_percentage_bydate> sla_percentage_bydate { get; set; }
        public virtual DbSet<mail_sent> mail_sent { get; set; }
        public virtual DbSet<mail_scheduled_task> mail_scheduled_task { get; set; }
    
        public virtual ObjectResult<slaClosedProjectByDate_Result> slaClosedProjectByDate(Nullable<int> monthvalue, Nullable<int> yearvalue)
        {
            var monthvalueParameter = monthvalue.HasValue ?
                new ObjectParameter("monthvalue", monthvalue) :
                new ObjectParameter("monthvalue", typeof(int));
    
            var yearvalueParameter = yearvalue.HasValue ?
                new ObjectParameter("yearvalue", yearvalue) :
                new ObjectParameter("yearvalue", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<slaClosedProjectByDate_Result>("slaClosedProjectByDate", monthvalueParameter, yearvalueParameter);
        }
    
        public virtual ObjectResult<slaClosedProjectByDateByRow_Result> slaClosedProjectByDateByRow(Nullable<int> monthvalue, Nullable<int> yearvalue, Nullable<int> pageStart, Nullable<int> pageEnd)
        {
            var monthvalueParameter = monthvalue.HasValue ?
                new ObjectParameter("monthvalue", monthvalue) :
                new ObjectParameter("monthvalue", typeof(int));
    
            var yearvalueParameter = yearvalue.HasValue ?
                new ObjectParameter("yearvalue", yearvalue) :
                new ObjectParameter("yearvalue", typeof(int));
    
            var pageStartParameter = pageStart.HasValue ?
                new ObjectParameter("pageStart", pageStart) :
                new ObjectParameter("pageStart", typeof(int));
    
            var pageEndParameter = pageEnd.HasValue ?
                new ObjectParameter("pageEnd", pageEnd) :
                new ObjectParameter("pageEnd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<slaClosedProjectByDateByRow_Result>("slaClosedProjectByDateByRow", monthvalueParameter, yearvalueParameter, pageStartParameter, pageEndParameter);
        }
    
        public virtual ObjectResult<slaOpenProject_Result> slaOpenProject()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<slaOpenProject_Result>("slaOpenProject");
        }
    
        public virtual ObjectResult<slaUsersMail_Result> slaUsersMail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<slaUsersMail_Result>("slaUsersMail");
        }
    }
}
