//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class journal_details
    {
        public int id { get; set; }
        public int journal_id { get; set; }
        public string property { get; set; }
        public string prop_key { get; set; }
        public string old_value { get; set; }
        public string value { get; set; }
    }
}
