//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_sent
    {
        public int ticket_id { get; set; }
        public string address { get; set; }
        public string sent_time { get; set; }
        public string last_sent_percentage { get; set; }
    }
}
