//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages
    {
        public int id { get; set; }
        public int board_id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string subject { get; set; }
        public string content { get; set; }
        public Nullable<int> author_id { get; set; }
        public int replies_count { get; set; }
        public Nullable<int> last_reply_id { get; set; }
        public System.DateTime created_on { get; set; }
        public System.DateTime updated_on { get; set; }
        public Nullable<bool> locked { get; set; }
        public Nullable<int> sticky { get; set; }
    }
}
