//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public int id { get; set; }
        public Nullable<int> project_id { get; set; }
        public string title { get; set; }
        public string summary { get; set; }
        public string description { get; set; }
        public int author_id { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public int comments_count { get; set; }
    }
}
