//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class open_id_authentication_associations
    {
        public int id { get; set; }
        public Nullable<int> issued { get; set; }
        public Nullable<int> lifetime { get; set; }
        public string handle { get; set; }
        public string assoc_type { get; set; }
        public byte[] server_url { get; set; }
        public byte[] secret { get; set; }
    }
}
