//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class projects
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string homepage { get; set; }
        public bool is_public { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
        public string identifier { get; set; }
        public int status { get; set; }
        public Nullable<int> lft { get; set; }
        public Nullable<int> rgt { get; set; }
        public bool inherit_members { get; set; }
        public Nullable<int> default_version_id { get; set; }
        public Nullable<int> default_assigned_to_id { get; set; }
        public string activity_report_settings { get; set; }
    }
}
