//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class repositories
    {
        public int id { get; set; }
        public int project_id { get; set; }
        public string url { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string root_url { get; set; }
        public string type { get; set; }
        public string path_encoding { get; set; }
        public string log_encoding { get; set; }
        public string extra_info { get; set; }
        public string identifier { get; set; }
        public Nullable<bool> is_default { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
    }
}
