//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> position { get; set; }
        public Nullable<bool> assignable { get; set; }
        public int builtin { get; set; }
        public string permissions { get; set; }
        public string issues_visibility { get; set; }
        public string users_visibility { get; set; }
        public string time_entries_visibility { get; set; }
        public bool all_roles_managed { get; set; }
        public string settings { get; set; }
    }
}
