//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sla_percentage_bydate
    {
        public int Id { get; set; }
        public int PercentYear { get; set; }
        public int PercentMonth { get; set; }
        public float SuccessfulPercentage { get; set; }
        public float FailedPercentage { get; set; }
        public bool IsDeleted { get; set; }
        public long DeleterUserId { get; set; }
        public System.DateTime DeletionTime { get; set; }
        public System.DateTime LastModificationTime { get; set; }
        public System.DateTime CreationTime { get; set; }
    }
}
