//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class time_entries
    {
        public int id { get; set; }
        public int project_id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> issue_id { get; set; }
        public float hours { get; set; }
        public string comments { get; set; }
        public int activity_id { get; set; }
        public System.DateTime spent_on { get; set; }
        public int tyear { get; set; }
        public int tmonth { get; set; }
        public int tweek { get; set; }
        public System.DateTime created_on { get; set; }
        public System.DateTime updated_on { get; set; }
    }
}
