//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class trackers
    {
        public int id { get; set; }
        public string name { get; set; }
        public bool is_in_chlog { get; set; }
        public Nullable<int> position { get; set; }
        public bool is_in_roadmap { get; set; }
        public Nullable<int> fields_bits { get; set; }
        public Nullable<int> default_status_id { get; set; }
    }
}
