//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id { get; set; }
        public string login { get; set; }
        public string hashed_password { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public bool admin { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> last_login_on { get; set; }
        public string language { get; set; }
        public Nullable<int> auth_source_id { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
        public string type { get; set; }
        public string identity_url { get; set; }
        public string mail_notification { get; set; }
        public string salt { get; set; }
        public bool must_change_passwd { get; set; }
        public Nullable<System.DateTime> passwd_changed_on { get; set; }
    }
}
