//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_preferences
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string others { get; set; }
        public Nullable<bool> hide_mail { get; set; }
        public string time_zone { get; set; }
    }
}
