//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class watchers
    {
        public int id { get; set; }
        public string watchable_type { get; set; }
        public int watchable_id { get; set; }
        public Nullable<int> user_id { get; set; }
    }
}
