//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wiki_redirects
    {
        public int id { get; set; }
        public int wiki_id { get; set; }
        public string title { get; set; }
        public string redirects_to { get; set; }
        public System.DateTime created_on { get; set; }
        public int redirects_to_wiki_id { get; set; }
    }
}
