//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iksap.ItsmReporting.Web.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class workflows
    {
        public int id { get; set; }
        public int tracker_id { get; set; }
        public int old_status_id { get; set; }
        public int new_status_id { get; set; }
        public int role_id { get; set; }
        public bool assignee { get; set; }
        public bool author { get; set; }
        public string type { get; set; }
        public string field_name { get; set; }
        public string rule { get; set; }
    }
}
